"""PostgreSQL/pgvector tabular storage backend.

Extends the dialect-agnostic :class:`cbrkit.indexable.sqlalchemy_async`
base with two system columns that are populated automatically from the
``value_column`` (the embeddable text column):

- ``pgvector_column`` (:class:`PGVECTOR`) — dense embedding of the value
  column, used for ANN search.
- ``tsvector_column`` (:class:`TSVECTOR`, generated by Postgres from the
  value column) — sparse FTS index target.

The storage also overrides the base's portable upsert with
``INSERT ... ON CONFLICT DO UPDATE`` for a single-round-trip write path.

The simplest setup stores plain strings (``V = str``) in a cbrkit-built
table::

    storage = pgvector_async(
        url=..., value_column="body", pgvector_dim=384, conversion_func=embed,
    )
    await storage.put_index({"a": "red sedan"})  # index -> {"a": "red sedan"}

For typed rows, pass a SQLAlchemy mapped *model* (host-created) — compose
:class:`PGVECTOR` and :class:`TSVECTOR` (re-exported here for convenience)
directly in it and point ``value_column`` at the embeddable column::

    from cbrkit.indexable import PGVECTOR, TSVECTOR
    import sqlalchemy as sa
    from sqlalchemy.orm import Mapped, mapped_column

    class Chunk(Base):
        __tablename__ = "chunks"
        id: Mapped[str] = mapped_column(primary_key=True)
        body: Mapped[str]
        _pgvec: Mapped[Any] = mapped_column(PGVECTOR(384), nullable=False)
        _tsvec: Mapped[Any] = mapped_column(
            TSVECTOR(),
            sa.Computed(
                sa.func.to_tsvector(sa.literal("english"), sa.column("body")),
                persisted=True,
            ),
            nullable=False,
        )

    storage = pgvector_async(url=..., model=Chunk, value_column="body", ...)
"""

from collections.abc import (
    Mapping,
    Sequence,
)
from dataclasses import dataclass
from typing import Any, ClassVar, Literal, cast

import numpy as np
import sqlalchemy as sa
from pgvector.sqlalchemy import HALFVEC, Vector as PGVECTOR
from sqlalchemy.dialects.postgresql import TSVECTOR, insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncConnection

from ..helpers import forward_fields, run_coroutine
from ..typing import (
    BatchConversionFunc,
    NumpyArray,
)
from ._common import PG_METRICS
from .sqlalchemy import sqlalchemy, sqlalchemy_async

# vector_type -> (HNSW opclass prefix, SQLAlchemy column type).  Both
# float32 (`vector`) and half-precision (`halfvec`, ~2x smaller) share the
# same distance comparator methods, so only the column type and opclass
# prefix differ.
_PG_VECTOR_TYPES: dict[Literal["float32", "halfvec"], tuple[str, Any]] = {
    "float32": ("vector", PGVECTOR),
    "halfvec": ("halfvec", HALFVEC),
}


def _tsvector_computed_clause(source: str, config: str) -> sa.Computed:
    """Persisted ``to_tsvector(<config>, <source>)`` clause."""
    return sa.Computed(
        sa.func.to_tsvector(sa.literal(config), sa.column(source)),
        persisted=True,
    )


@dataclass(slots=True)
class pgvector_async[K: int | str, V = Mapping[str, Any]](sqlalchemy_async[K, V]):
    """Async PostgreSQL/pgvector tabular storage.

    Extends :class:`sqlalchemy_async` with two system columns derived from
    the inherited :paramref:`value_column` (the embeddable text column):

    - ``pgvector_column`` carries a dense embedding (computed in Python via
      :paramref:`conversion_func` and inserted on write).
    - ``tsvector_column`` is a Postgres-generated ``TSVECTOR`` over the
      value column.

    The *value_column* is the single text-field knob shared with the other
    backends: with no *model* / *table* / *reflect* cbrkit builds a
    one-column table and ``V = str``; with a *model* / host table it names
    which existing column is embedded and FTS-indexed.

    Args:
        pgvector_column / tsvector_column: System column names (underscored by
            convention to signal "owned by cbrkit").
        pgvector_dim: Embedding dimension.  Required for ``manage_schema=
            True`` and *index_type* ∈ {``"dense"``, ``"hybrid"``}.
        vector_type: Stored element type — ``"float32"`` (``vector``, exact)
            or ``"halfvec"`` (half precision, ~2x smaller with negligible
            recall loss).  Both share the same distance metrics; for a
            host-supplied *model*, declare the column with the matching
            re-exported type (:class:`PGVECTOR` / :class:`HALFVEC`).
        index_type: ``"dense"`` (HNSW only), ``"sparse"`` (GIN only), or
            ``"hybrid"`` (both).
        tsvector_config: PostgreSQL FTS configuration for the
            ``tsvector_column`` generator.
        metric_type: Distance metric used by the HNSW index (and mirrored
            at search time by the retriever wrapper).
        conversion_func: Embedding function.  Required for ``"dense"`` /
            ``"hybrid"`` index types.
    """

    _PARAM_LIMIT: ClassVar[int] = 65_535

    pgvector_column: str = "_pgvec"
    tsvector_column: str = "_tsvec"
    pgvector_dim: int | None = None
    vector_type: Literal["float32", "halfvec"] = "float32"
    index_type: Literal["dense", "sparse", "hybrid"] = "dense"
    tsvector_config: str = "english"
    metric_type: Literal["cosine", "ip", "l2"] = "cosine"
    conversion_func: BatchConversionFunc[str, NumpyArray] | None = None

    @property
    def has_dense(self) -> bool:
        """Whether this storage maintains a dense vector index."""
        return self.index_type in ("dense", "hybrid")

    @property
    def has_sparse(self) -> bool:
        """Whether this storage maintains a sparse FTS index."""
        return self.index_type in ("sparse", "hybrid")

    def _validate_init(self) -> None:
        super(pgvector_async, self)._validate_init()
        if self.value_column is None:
            raise ValueError("value_column is required for pgvector")
        if self.table is not None and self.value_column not in self.table.columns:
            raise ValueError(
                f"value_column={self.value_column!r} must be a column of the "
                "model / table"
            )
        if self.has_dense and self.conversion_func is None:
            raise ValueError(
                f"conversion_func is required for index_type={self.index_type!r}"
            )
        if (
            self.manage_schema
            and self.table is None
            and self.has_dense
            and self.pgvector_dim is None
        ):
            raise ValueError(
                "pgvector_dim is required when manage_schema=True and "
                f"index_type={self.index_type!r}"
            )
        if self.pgvector_dim is not None and self.pgvector_dim <= 0:
            raise ValueError(
                f"pgvector_dim must be a positive int (got {self.pgvector_dim!r})"
            )

    def _system_columns(self) -> Sequence[sa.Column[Any]]:
        cols: list[sa.Column[Any]] = []
        if self.has_dense:
            assert self.pgvector_dim is not None
            _, col_type = _PG_VECTOR_TYPES[self.vector_type]
            cols.append(
                sa.Column(self.pgvector_column, col_type(self.pgvector_dim), nullable=False)
            )
        if self.has_sparse:
            assert self.value_column is not None
            cols.append(
                sa.Column(
                    self.tsvector_column,
                    TSVECTOR(),
                    _tsvector_computed_clause(self.value_column, self.tsvector_config),
                    nullable=False,
                )
            )
        return cols

    def _system_column_names(self) -> frozenset[str]:
        names: set[str] = set()
        if self.has_dense:
            names.add(self.pgvector_column)
        if self.has_sparse:
            names.add(self.tsvector_column)
        return frozenset(names)

    def _pre_create_ddl(self, sync_conn: sa.Connection) -> None:
        if self.has_dense:
            sync_conn.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))

    def _create_system_indexes(self, sync_conn: sa.Connection) -> None:
        if self.has_dense:
            prefix, _ = _PG_VECTOR_TYPES[self.vector_type]
            opclass = f"{prefix}_{PG_METRICS[self.metric_type].ops_suffix}_ops"
            sa.Index(
                f"ix_{self._table.name}_{self.pgvector_column}",
                self._table.c[self.pgvector_column],
                postgresql_using="hnsw",
                postgresql_ops={self.pgvector_column: opclass},
            ).create(sync_conn, checkfirst=True)

        if self.has_sparse:
            sa.Index(
                f"ix_{self._table.name}_{self.tsvector_column}",
                self._table.c[self.tsvector_column],
                postgresql_using="gin",
            ).create(sync_conn, checkfirst=True)

    def _populate_system_columns(self, rows: list[dict[str, Any]]) -> None:
        if not self.has_dense:
            return
        assert self.conversion_func is not None
        assert self.value_column is not None
        texts = [row[self.value_column] for row in rows]
        for row, vec in zip(rows, self.conversion_func(texts), strict=True):
            row[self.pgvector_column] = np.asarray(vec).tolist()

    async def _do_upsert(
        self, conn: AsyncConnection, rows: list[dict[str, Any]]
    ) -> None:
        if not rows:
            return
        columns = list(rows[0])
        update_cols = [c for c in columns if c != self.key_column]
        batch_size = max(1, self._PARAM_LIMIT // len(columns))

        for start in range(0, len(rows), batch_size):
            chunk = rows[start : start + batch_size]
            stmt = pg_insert(self._table).values(chunk)
            await conn.execute(
                stmt.on_conflict_do_update(
                    index_elements=[self._table.c[self.key_column]],
                    set_={c: stmt.excluded[c] for c in update_cols},
                )
            )

    # -- re-embed helper -----------------------------------------------------

    async def reembed_all(self, batch_size: int = 1000) -> int:
        """Recompute embeddings for every row in place.

        Iterates pages of *batch_size* rows ordered by primary key, re-runs
        :paramref:`conversion_func` on the text column, and UPDATEs the
        vector column.  Other columns are not touched.

        Returns:
            The total number of rows updated.
        """
        if not self.has_dense:
            return 0
        assert self.conversion_func is not None
        assert self.value_column is not None

        kc = self._table.c[self.key_column]
        tc = self._table.c[self.value_column]
        total = 0

        async with self._engine.begin() as conn:
            await self._ensure_schema(conn)

            offset = 0
            while True:
                rows = (
                    await conn.execute(
                        sa.select(kc, tc).order_by(kc).limit(batch_size).offset(offset)
                    )
                ).all()
                if not rows:
                    break

                keys = [k for k, _ in rows]
                texts = [t for _, t in rows]
                vecs = self.conversion_func(texts)

                await conn.execute(
                    sa.update(self._table)
                    .where(self._table.c[self.key_column] == sa.bindparam("k"))
                    .values({self.pgvector_column: sa.bindparam("v")}),
                    [
                        {"k": k, "v": np.asarray(vec).tolist()}
                        for k, vec in zip(keys, vecs, strict=True)
                    ],
                )
                total += len(rows)
                offset += batch_size

        return total


@dataclass(slots=True)
class pgvector[K: int | str, V = Mapping[str, Any]](sqlalchemy[K, V]):
    """Sync facade over :class:`pgvector_async`.

    Adds the pgvector-specific configuration on top of the
    :class:`cbrkit.indexable.sqlalchemy` sync facade and overrides
    :meth:`_build_async` to construct a :class:`pgvector_async`.
    """

    pgvector_column: str = "_pgvec"
    tsvector_column: str = "_tsvec"
    pgvector_dim: int | None = None
    vector_type: Literal["float32", "halfvec"] = "float32"
    index_type: Literal["dense", "sparse", "hybrid"] = "dense"
    tsvector_config: str = "english"
    metric_type: Literal["cosine", "ip", "l2"] = "cosine"
    conversion_func: BatchConversionFunc[str, NumpyArray] | None = None

    def _build_async(self) -> pgvector_async[K, V]:
        return pgvector_async[K, V](
            engine=self._engine, **forward_fields(self, exclude={"url"})
        )

    @property
    def async_storage(self) -> pgvector_async[K, V]:
        """The wrapped async storage (used by sync retriever facades)."""
        return cast("pgvector_async[K, V]", self._async)

    def reembed_all(self, batch_size: int = 1000) -> int:
        return run_coroutine(self.async_storage.reembed_all(batch_size))


__all__ = [
    "HALFVEC",
    "PGVECTOR",
    "TSVECTOR",
    "pgvector",
    "pgvector_async",
]
