from collections.abc import Callable
from dataclasses import dataclass
from typing import override

from ..typing import Casebase, MapAdaptationFunc

__all__ = [
    "auto_key",
]


@dataclass(slots=True, frozen=True)
class auto_key[K, V](MapAdaptationFunc[K, V]):
    """Store a case using a key generated by a callable.

    Args:
        key_func: A callable that generates a new key given the current casebase.

    Examples:
        >>> func = auto_key(key_func=lambda cb: max(cb.keys(), default=-1) + 1)
        >>> result = func({0: "a", 1: "b"}, "c")
        >>> result[2]
        'c'
    """

    key_func: Callable[[Casebase[K, V]], K]

    @override
    def __call__(
        self,
        casebase: Casebase[K, V],
        query: V,
        /,
    ) -> Casebase[K, V]:
        new_key = self.key_func(casebase)
        updated = dict(casebase)
        updated[new_key] = query

        return updated
